version: '3.8'

services:
  backend:
    build: ./backend
    environment:
      DATABASE_URL: sqlite:///./family_tasks.db
      SECRET_KEY: your-secret-key-change-in-production
      ALLOWED_ORIGINS: http://localhost:4100,http://localhost:5173,http://localhost
    ports:
      - "3100:3100"
    volumes:
      - ./backend:/app
      - sqlite_data:/app/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 3100 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3100/docs"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "4100:80"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:3100

volumes:
  sqlite_data:
